### PR TITLE
System test for spatial queries with non-point objects

### PR DESCRIPTION
**Pull request by geophile**

### CODE REVIEW

**Comment by MMcM** [comment]
A prepared statement is not recompiled when DDL occurs or statistics are generated. It looks like the embedded driver is missing a version check. It ought to have thrown an out-of-date statement exception, as Postgres would, I think.

Without some change to `GEO_WKT` overloads or the optimizer, a `CAST` to `VARCHAR` will mean that the spatial index is never used.

I think we have an outstanding issue about prepared statements and spatial cursors. Like maybe that they try to get the object(s) before `open`, so this might then tickle that.

**Comment by geophile** [comment]
Sorry, I didn't follow the last two paragraphs of MMcMs comment. I'll change the PreparedStatement to Statement, but I don't understand what cast is being referred to, nor what is being tickled.

**Comment by MMcM** [comment]
Sorry for not being more explicit.

The predicate being used is actually `geo_overlaps(geo_wkt(Cast(boxes.box AS MCOMPAT_ VARCHAR(65535, UTF8, UCS_BINARY) NULL)),geo_wkt($0))` and this is not recognized as compatible with an index on `geo_wkt(boxes.box)`. Which, strictly speaking, it isn't because of the truncation that the cast implies. As a result, a spatial index is not used.

If `MGeometryFunctions.MGEOWKT` is changed to `MString.TEXT`, the `CAST` goes away. And this error results if a prepared statement is used:

```
java.lang.NullPointerException: null
	at com.foundationdb.server.types.texpressions.TPreparedParameter$InnerEvaluation.evaluate(TPreparedParameter.java:82)
	at com.foundationdb.server.types.texpressions.TPreparedFunction$TEvaluatableFunction$1.get(TPreparedFunction.java:176)
	at com.foundationdb.server.types.texpressions.TPreparedFunction$TEvaluatableFunction$1.get(TPreparedFunction.java:170)
	at com.foundationdb.server.types.texpressions.TScalarBase.evaluate(TScalarBase.java:63)
	at com.foundationdb.server.types.texpressions.TValidatedScalar.evaluate(TValidatedScalar.java:51)
	at com.foundationdb.server.types.texpressions.TPreparedFunction$TEvaluatableFunction.evaluate(TPreparedFunction.java:157)
	at com.foundationdb.qp.expression.ExpressionRow.uncheckedValue(ExpressionRow.java:62)
	at com.foundationdb.qp.row.AbstractRow.value(AbstractRow.java:67)
	at com.foundationdb.qp.expression.RowBasedUnboundExpressions$ExpressionsAndBindings.value(RowBasedUnboundExpressions.java:81)
	at com.foundationdb.qp.storeadapter.indexcursor.IndexCursorSpatial_InBox.spatialObject(IndexCursorSpatial_InBox.java:244)
	at com.foundationdb.qp.storeadapter.indexcursor.IndexCursorSpatial_InBox.<init>(IndexCursorSpatial_InBox.java:121)
	at com.foundationdb.qp.storeadapter.indexcursor.IndexCursorSpatial_InBox.create(IndexCursorSpatial_InBox.java:104)
	at com.foundationdb.qp.storeadapter.indexcursor.IndexCursor.create(IndexCursor.java:108)
	at com.foundationdb.qp.storeadapter.PersistitIndexCursor.<init>(PersistitIndexCursor.java:104)
	at com.foundationdb.qp.storeadapter.FDBAdapter.newIndexCursor(FDBAdapter.java:109)
	at com.foundationdb.qp.operator.IndexScan_Default$LookaheadExecution.newCursor(IndexScan_Default.java:405)
	at com.foundationdb.qp.operator.LookaheadLeafCursor.<init>(LookaheadLeafCursor.java:172)
	at com.foundationdb.qp.operator.IndexScan_Default$LookaheadExecution.<init>(IndexScan_Default.java:420)
	at com.foundationdb.qp.operator.IndexScan_Default.cursor(IndexScan_Default.java:173)
	at com.foundationdb.qp.operator.GroupLookup_Default.cursor(GroupLookup_Default.java:139)
	at com.foundationdb.qp.operator.Select_HKeyOrdered.cursor(Select_HKeyOrdered.java:104)
	at com.foundationdb.qp.operator.Project_Default.cursor(Project_Default.java:92)
	at com.foundationdb.qp.operator.API.cursor(API.java:890)
	at com.foundationdb.qp.operator.API.cursor(API.java:895)
	at com.foundationdb.sql.embedded.ExecutableQueryOperatorStatement.execute(ExecutableQueryOperatorStatement.java:47)
	at com.foundationdb.sql.embedded.JDBCStatement.executeInternal(JDBCStatement.java:76)
	at com.foundationdb.sql.embedded.JDBCStatement.executeQueryInternal(JDBCStatement.java:131)
	at com.foundationdb.sql.embedded.JDBCPreparedStatement.executeQuery(JDBCPreparedStatement.java:103)
	at com.foundationdb.server.test.it.qp.SpatialQueryDT.spatialQueries(SpatialQueryDT.java:110)
```

The problem is that `create` is trying to access the parameter bindings to get the spatial object, but they aren't available until `open`. Cf. `IndexCursorUnidirectional.evaluateBoundaries`, which is the equivalent scan setup for an ordinary index.

So, we definitely need some system tests that include prepared statements with spatial boundaries as parameters. But it would be fine to get the test passing in simpler form first and then address that separately.

**Comment by MMcM** [comment]
If the query is executed using a non-prepared statement and with the spatial index, it fails due to duplicate rows. I believe there was some discussion about where duplicate elimination should take place and how it should be controlled.

The new source file is missing the standard header.

**Comment by nathanlws** [comment]
Replaced by #1687

**Pull request closed without merging**
