### PR TITLE
Support for WKT serialization of spatial objects

### PR DESCRIPTION
**Pull request by geophile**
Serialize spatial objects using WKB or WKT, depending on the type of the spatial object column (blob or text).

### CODE REVIEW

**Comment by MMcM** [comment]
I think it might be better to make `SpatialColumnHandler` remember the index's spatial function (WKT, WKB, JSON) and use that in `bind` rather than the source type.

**Comment by geophile** [comment]
> I think it might be better to make SpatialColumnHandler remember the index's spatial function (WKT, WKB, JSON) and use that in bind rather than the source type.

That's a good idea. My next pull request will extend the enums specifying function names, Index.IndexMethod, and ais.proto's IndexMethod. OK if I address this as part of that work?

**Comment by MMcM** [comment]
Yes, that sounds fine.

**Comment by nathanlws** [comment]
Approve

**Pull request merged**
