### PR TITLE
Explain except correctly

### PR DESCRIPTION
**Pull request by ScottDugas**
It behaves like `Union_Ordered` not `UnionAll_Default`

### CODE REVIEW

**Comment by nathanlws** [comment]
Unrelated to this change, I think, but the "all" qualifier seems to be in the output no matter what. Something off about the condition for it in getExplainer()?

**Comment by ScottDugas** [comment]
The suspicious bit of code is in [OperatorAssembler.assembleExcept](https://github.com/FoundationDB/sql-layer/blob/master/fdb-sql-layer-core/src/main/java/com/foundationdb/sql/optimizer/rule/OperatorAssembler.java#L1104) It checks isAll and then doesn't create an `Except_Ordered` with `removeDuplicates`. On the other hand, that boolean isn't really necessary for except, because if there's no duplicates in the left hand side, the `Except_Ordered` doesn't need to do anything to remove duplicates from the output, right?

**Comment by MMcM** [comment]
Yes. If an explicit sort is added, it makes sense to have it eliminate duplicates, because that is more space efficient and no less time efficient. If an explicit sort is not needed, then the operator needs to remove any duplicates. What is missing is logic there to ever decide that the input stream is already properly ordered and skip adding the explicit sort.

**Comment by nathanlws** [comment]
I see. So the behavior of the operator is different if the "all" isn't present but it is never constructed that way?

I see Intersect_Ordered has an `outputEqual` member as well. Should that also add the SET_OPTION when it's `true`?

**Comment by ScottDugas** [comment]
Yes, that is the situation for "all"

I think it makes sense to add the `SET_OPTION` for `Interesect_Ordered`, but I'm not entirely sure what it should be.

**Comment by nathanlws** [comment]
I believe it should be:

```
if (outputEqual)
    atts.put(Label.SET_OPTION, PrimitiveExplainer.getInstance("ALL"));
```

**Comment by nathanlws** [comment]
Thanks.

Approve

**Comment by nathanlws** [comment]
Approve

**Pull request merged**
