### PR TITLE
Fix WHERE NOT EXISTS error

### PR DESCRIPTION
**Pull request by hchandl**
Conditions in an anti join shouldn't be negated or moved to the outer node.

### CODE REVIEW

**Comment by nathanlws** [comment]
@ScottDugas You talked to @hchandl about this, right?

**Comment by ScottDugas** [comment]
Yes. To take it to the extreme, if you have the tables `A=[1,2,3]` and `B=[]`, the following would return all of A: `SELECT * FROM A WHERE NOT EXISTS (SELECT * FROM B WHERE F(A.x) && B.x=5)` regardless of the definition of `F()`.

**Comment by ScottDugas** [comment]
The reason it's different for semi vs anti join, is that a semi join is `A && B && C` whereas an anti join is `!(A && B && C) = !A || !B || !C` so you can't move one of the clauses across the MapNestedLoop, because that is an `&&` operation.

**Comment by nathanlws** [comment]
Sounds good then.

Approve

**Pull request merged**
