### PR TITLE
fix run IT with policy file, add test

### PR DESCRIPTION
**Pull request by SytzeH**
Extra line in pom file seemed to be needed to run IT with policy file

### CODE REVIEW

**Comment by ScottDugas** [comment]
This change causes `mvn test -Dtest=SomeIT` to also run with a policy file, whereas before it would only use the policy file when doing `mvn verify`, which seems worthwhile.

Approve

**Comment by SytzeH** [comment]
I'm not sure if the failures are related.

**Comment by ScottDugas** [comment]
I think they are related. It fails with:
```
Caused by: java.lang.IllegalArgumentException: A SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene40' does not exist. You need to add the corresponding JAR file supporting this SPI to your classpath.The current classpath supports the following names: []
```

It looks like the code is trying to get the classloader and then find classes in it, which I'm guessing is prevented by the IT policy file. I'm not sure why it wasn't failing before though. It's part of the failsafe run, and that already had a policy file. And I know that was working because it broke another test.

**Comment by MMcM** [comment]
#1578 had something similar due to leaving a context class loader set, which Lucene uses to find codecs.

**Comment by MMcM** [comment]
The newly added test has a routine that is supposed to fail, which probably indicates that the thread's context class loader reset isn't happening inside `finally`.

**Comment by SytzeH** [comment]
Thanks all the help. This should fix it, probably due to the order of testing from the Yamls I didn't get them to fail locally.

**Comment by SytzeH** [comment]
updated

**Comment by MMcM** [comment]
Approve

**Pull request merged**
