### PR TITLE
Correct and comment ConstantFolder#isIdempotent()

### PR DESCRIPTION
**Pull request by nathanlws**
RAND didn't belong, the other function names weren't quite right and a couple comments for clarifying distinction from constant functions.

### CODE REVIEW

**Comment by tjoneslo** [comment]
IIRC, we made `rand` Idempotent to control when and how it got called. As long as you're ok with that changing, go ahead and approve.

**Comment by nathanlws** [comment]
It's not idempotent though.

As the new comments in ConstantFolder say, an idempotent function must return the same value for any given invocation in the same query. Zero argument `RAND` has no such guarantee as currently implemented.

**Comment by MMcM** [comment]
It was clearly a mistake. That code was added in 1f959b927b353efccaf938901de872f99ce6352e even before the first implementation in f6549ee04bc8528039053662a133b26a58285f89.

**Comment by tjoneslo** [comment]
I recall the discussion was completely separate from the implementation. And was trying to support something which shouldn't have been in the first place. 

Approve

**Pull request merged**
